# Generated by Django 3.0.6 on 2020-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201119_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(height_field=50, upload_to='imgs/', width_field=50),
        ),
    ]
