export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const VERIFICATION = 'VERIFICATION';
export const USER_DATA = 'USER_DATA';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const VERIFICATION_ERROR = 'VERIFICATION_ERROR';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const CREATE_MOVIE = 'CREATE_MOVIE';
export const CREATE_MOVIE_ERROR = 'CREATE_MOVIE_ERROR';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';

export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = 'REMOVE_LIKE';

export const GET_GENRES = 'GET_GENRES';
export const SET_GENRES = 'SET_GENRES';
export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';

export const LIKE_MOVIE = 'LIKE_MOVIE';
export const DISLIKE_MOVIE = 'DISLIKE_MOVIE';

export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const SET_MOVIE_BY_ID = 'SET_MOVIE_BY_ID';
export const GET_MOVIE_BY_ID_ERROR = 'GET_MOVIE_BY_ID_ERROR';

export const LOGGED_USER_DATA = 'LOGGED_USER_DATA';
export const LOGGED_USER_DATA_ERROR = 'LOGGED_USER_DATA_ERROR';

export const SET_USER = 'SET_USER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const FILTER_MOVIES = 'FILTER_MOVIES';
export const FILTER_MOVIES_ERROR = 'FILTER_MOVIES_ERROR';
