# Generated by Django 3.0.6 on 2020-11-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0002_auto_20201118_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
