# Generated by Django 3.0.6 on 2020-11-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0004_auto_20201124_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
