# Generated by Django 3.0.6 on 2020-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0007_auto_20201124_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='times_viewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
