# Generated by Django 3.0.6 on 2020-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0010_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
